// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgmtU0UAQik4CC7OGB_KxY6XmLMpB-1GE',
    appId: '1:1070882229371:web:543a4fe2b8c83c4f76e6de',
    messagingSenderId: '1070882229371',
    projectId: 'my-shop-v1',
    authDomain: 'my-shop-v1.firebaseapp.com',
    storageBucket: 'my-shop-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe3gY8Z6OnE2_NoqeTN8SXKjZ9fNtGGRk',
    appId: '1:1070882229371:android:2de87898d10b5c4e76e6de',
    messagingSenderId: '1070882229371',
    projectId: 'my-shop-v1',
    storageBucket: 'my-shop-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDdYOns-5NDtlqfafOLbZ1-AUQG_9m75Q',
    appId: '1:1070882229371:ios:0a9a81b1c93d4b6776e6de',
    messagingSenderId: '1070882229371',
    projectId: 'my-shop-v1',
    storageBucket: 'my-shop-v1.firebasestorage.app',
    iosBundleId: 'com.example.myShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDdYOns-5NDtlqfafOLbZ1-AUQG_9m75Q',
    appId: '1:1070882229371:ios:0a9a81b1c93d4b6776e6de',
    messagingSenderId: '1070882229371',
    projectId: 'my-shop-v1',
    storageBucket: 'my-shop-v1.firebasestorage.app',
    iosBundleId: 'com.example.myShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgmtU0UAQik4CC7OGB_KxY6XmLMpB-1GE',
    appId: '1:1070882229371:web:cf849ce7bed6f67376e6de',
    messagingSenderId: '1070882229371',
    projectId: 'my-shop-v1',
    authDomain: 'my-shop-v1.firebaseapp.com',
    storageBucket: 'my-shop-v1.firebasestorage.app',
  );
}
